---
title: "League of Legends League Map"
author: "Lujia Deng"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
theme_set(theme_bw())
library(ggmap)
library(tidyverse)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
```


```{r pressure, echo=FALSE}

# pull country data from rnaturalearth
world <- ne_countries(scale = "medium", returnclass = "sf")


# league region list for LEC, PCS, LLA

LEC_dat <- read.csv("./data_folder/LEC.csv")
LEC_list <- as.character(LEC_dat$State)
LEC_list[14] <- 'Ireland'

PCS_list = c('HKG', 'TWN', 'MAC', 'SGP')
LLA_list = c('ARG', 'MEX', 'CHL', 'CRI')


# add a 'league' column
## first creates dummy variables
world_new <- world %>% 
  mutate(LPL = if_else(admin=='China', 1, 0)) %>% 
  mutate(LCS = if_else((admin=='Canada')|(admin=='United States of America'), 1, 0)) %>%
  mutate(LEC = if_else(admin %in% LEC_list, 1, 0)) %>%
  mutate(LCK = if_else(admin == 'South Korea', 1, 0)) %>%
  mutate(PCS = if_else(adm0_a3 %in% PCS_list, 1, 0)) %>%
  mutate(CBLOL = if_else(admin == 'Brazil', 1, 0)) %>%
  mutate(LCL = if_else(admin == 'Russia', 1, 0)) %>%
  mutate(LJL = if_else(admin == 'Japan', 1, 0)) %>%
  mutate(OPL = if_else(admin == 'Australia', 1, 0)) %>%
  mutate(LLA = if_else(adm0_a3 %in% LLA_list, 1, 0)) %>%
  mutate(VCS = if_else(admin == 'Vietnam', 1, 0)) %>%
  mutate(TCL = if_else(admin == 'Turkey', 1, 0))

## combine dummy variables into one column

world_new$league <- names(world_new[65:76])[apply(world_new[65:76], 1, match, x=1)]
world_new[is.na(world_new)] <- 'N/A'

# world_new[world_new$OPL == 1,]

# Draw league map

map_color_pal <- c('deepskyblue1', 'red2', "royalblue", 'lightskyblue2', 'blue1', 'forestgreen','cornsilk1', 'orangered1', 'darkgoldenrod2','dodgerblue1','gold1', 'darkolivegreen2')

world_new$league <- factor(world_new$league, 
                           levels = c('LCK', 'LPL','LEC','LCS','PCS','CBLOL','LCL','LJL','LLA','OPL','TCL','VCS'))

league_map <- ggplot(data = world_new) + geom_sf(aes(fill=league), alpha=0.7) + xlab("Longitude") + ylab("Latitude") + labs(fill = "Tier-1 Leagues")
league_map <- league_map + scale_fill_manual(values=map_color_pal)
league_map <- league_map + ggtitle("League of Legends Tier-1 League Map", subtitle = "There are 12 tier-1 professional leagues around the world")

league_map

ggsave("league_map.png")
```
